services:

  dump1090:
    build:
      context: ../
      dockerfile: docker/dump1090.dockerfile
    image: dump1090:1.0
    ports:
      - 30003:30003
    privileged: true
    environment:
      - LATITUDE=55.3846
      - LONGITUDE=37.4450

  sbs-receiver:
    build:
      context: ../
      dockerfile: docker/sbs-receiver.dockerfile
    image: sbs-receiver:1.2
    environment:
      - DUMP1090_HOST=dump1090
      - DUMP1090_PORT=30003
      - WEBSERVER_HOST=web-server
      - WEBSERVER_PORT=5000

  web-server:
    build:
      context: ../
      dockerfile: docker/web-server.dockerfile
    image: web-server:0.1
    ports:
      - 5000:5000
    environment:
      - HOST=0.0.0.0
      - PORT=5000

  postgres:
    image: postgres:12.6
    ports:
      - 5432:5432
    volumes:
      - /var/postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
