services:

  dump1090:
    image: dump1090:1.0
    ports:
      - 30003:30003
    privileged: true
    environment:
      - LATITUDE=55.3846
      - LONGITUDE=37.4450

  sbs-receiver:
    image: sbs-receiver:1.1
    environment:
      - DUMP1090_HOST=dump1090
      - DUMP1090_PORT=30003
