services:

  dump1090:
    image: dump1090:1.0
    ports:
      - 30003:30003
    privileged: true
    environment:
      - LATITUDE=55.3846
      - LONGITUDE=37.4450

  rabbitmq:
    hostname: my-rabbit
    image: rabbitmq:3.8.9
    ports:
      - 5672:5672
    environment:
      - RABBITMQ_DEFAULT_USER=rabbitmq_user
      - RABBITMQ_DEFAULT_PASS=rabbitmq_pass
      - RABBITMQ_DEFAULT_VHOST=plane_vhost

  sbs-receiver:
    image: sbs-receiver:1.0
    environment:
      - DUMP1090_HOST=dump1090
      - DUMP1090_PORT=30003
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USER=rabbitmq_user
      - RABBITMQ_PASS=rabbitmq_pass
      - RABBITMQ_VHOST=plane_vhost
      - RABBITMQ_EXCHANGE_NAME=sbs_message_exchange
      - RABBITMQ_EXCHANGE_TYPE=direct
